name: 'Initialize'
description: 'Install all necessary programs'
runs:
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Install Dependecies
        run: npm install