name: Checks before merge

on:
  push:
    branches:
      - main
      - dev
      - stage

jobs:
  hardhat_test:
    name: hardhat test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Install Dependecies
        run: npm install
      - name: Run tests
        run: npm run test
  