name: Checks before merge

on:
  push:
    branches:
      - main
      - dev
      - stage

jobs:
  hardhat-test:
    name: hardhat test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/init
      - name: Run tests
        run: npm run test

  linter-check:
    name: linters Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/init
      - name: Run solhint
        run: npm run solhint
      - name: Run eslint
        run: npm run eslint
